language: python
addons:
  ssh_known_hosts:
    - 54.229.70.158
    - ec2-54-229-70-158.eu-west-1.compute.amazonaws.com
python:
- '3.3'
install: "./djangosetup.sh"
script: "./testbuild.sh"
before_deploy:
  - "./package.sh"
  - pip install fabric
  - echo "$DEPLOY_KEY" >> ~/.ssh/deploy_key.pem
  - yes yes | git remote add live ssh://ubuntu@ec2-54-229-70-158.eu-west-1.compute.amazonaws.com/home/ubuntu/repo/site.git
deploy:
  provider: script
  script: ./empty.sh
  skip_cleanup: true
  on:
    branch: dev
