language: python
python:
- '3.3'
install: "./djangosetup.sh"
script: "./testbuild.sh"
before_deploy: "./package.sh"
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: dev
