language: python
addons:
  ssh_known_hosts:
    - 54.229.70.158
    - ec2-54-229-70-158.eu-west-1.compute.amazonaws.com
python:
- '3.3'
install: "./djangosetup.sh"
script: "./testbuild.sh"
before_deploy:
  - "./package.sh"
  - pip install fabric3 gitric
deploy:
  provider: script
  script: fab -H $DEPLOY_HOSTS -p $DEPLOY_PASS
  skip_cleanup: true
  on:
    branch: dev
