language: python
python:
- '3.3'
install: "./djangosetup.sh"
script: "./testbuild.sh"
before_deploy: "./package.sh"
deploy:
- provider: script
  region: eu-west-1
  skip_cleanup: true
  on: &3
    branch: dev
