language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- 3.6-dev
install: "./djangosetup.sh"
script: "./testbuild.sh"
before_deploy: "./package.sh"
deploy:
- provider: s3
  access_key_id: &1
    secure: rQwT3wCa+iWT4zIu9zNFt1nEKcbObtECIjZ+4TsHEwXeLDgmpMK8EQN4fYFhnc6ER1D3KfiiBNnYOA6DNTU+ozB3aRy9f5uKT2KLzcS6hpPaCmcOO18oVsL5i/vs4QG45QoNLd7P54o4KWw1tvV7OzxQWfARw8hb+akgaSsCk6XzVkSbKDcss91LuBVrF++RmP2KffNQn08lHvdd0vQT14qzFaYpoA7g6+pLGsHyfjUy+HjDGhuHAczo9lfqfUYq9izsKyi/deuocRexpCfA11ZZr77r54H0EhToJIlPPAWmQSq5/eWurzUXGcjZpY6UiLsnscuaXd9xRBLejG50i1BqFpkhd2+A2TLBZ/MS/9EzzYHPxcq+uhQbWkAnMHb9vh3TwLwQsq3WRxF4WiFdVfppTJ4RrfIxlQkiKUIuvk8UVtg6TlWCrY+NKQ4dIR5EKjqMmYKyTl9cmKzJw0vFQBpB99/ck9uW+Apm8d/7Uzi5eyhlL7RUpN5wOnxgD4pKXeNdKhvC5zMKgz+9UkPkBY4tbcj3DMqjB0m2sDCj+Mr2aQ3SucUql6rziUgXBvocAy/q0s15QbuB7MsA1Slktuuq0BWx00d593e63jiuCsGnZLi5DBNZxgJz9sRtgg15xw3XXJHhWm7TCO9JPruiR13bjytG9j68on5rJBYGbzU=
  secret_access_key: &2
    secure: dn9T8a8h5yH2FIp0R7sYZxmrkvq7v+COPuDqsKFnDKbw+Pn0FvxwvqRZPJdF3jlbCEPVBDzDoiwlc/1Cpja19JoVKimK116ZXkJ8FU9bDMdWboRLN56iEO+NtovrGr76pJbaEv2Iohipn4U/GqYqyvCRQN+2crvJ5YLud8CuPy17Sx72t7+3UUCIsfhe2m52y4Sjj6JiKPg1grC8FdCB8jbD+5VRMdgyPuerXf0xjNrPQHwgMnN3k2KvhrvSji8P6VCDpIkQZsqxdT+k5850hAJAhATH4waHl3t90IUlqntiNfjKG+0inGo6fccMpVyEX3d8Pr7jbAljHCCig6teJa2CSOA33HIYyVVeBmEosjLwUM0DZB/EFl9ejhfZ/Xno052K+KM488fnZk09OkJyz761tdFiOLnE6LMc5VdEgCxX8bupVZ3CxAsS8B1VGFqh/urfsBO7nKw019Ntd1nNQamgWzbQl1gHjPfXqU/msf5ix8n9R5bFe1X+MI3PPA/Zj0zjGLDBhNcoeWL/4xvYTyTD3hJhNyq1sN//NuhyjqggpBcxeepT0p7neJeD2Mw1IwbACh66J43AmjZzJTIqI0boHI3jLWh8uaByXwD46DuhRA9naAhlnr0kgci2TFy1bEhd2A5OP8sKNqiwfsBSuRjYZaPXBBwqIdh1dnarwSI=
  local_dir: rdy4deploy_ref_manager
  region: eu-central-1
  skip_cleanup: true
  bucket: refmanager-codedeploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: refmanager-codedeploy
  key: latest.zip
  bundle_type: zip
  application: RefManager
  deployment_group: Staging
