language: python
python:
- '3.3'
install: "./djangosetup.sh"
script: "./testbuild.sh"
before_deploy:
  - "./package.sh"
  - ls
  - echo "Now running ssh agent"
  - eval "$(ssh-agent -s)"
  - echo "$DEPLOY_KEY" > ~/.ssh/deploy_key.pem
  - chmod 600 ~/.ssh/deploy_key.pem
  - echo "Now adding remote"
  - yes yes | git remote add live ssh://ubuntu@ec2-54-229-70-158.eu-west-1.compute.amazonaws.com/home/ubuntu/repo/site.git
  - echo "Now pushing"
  - echo "54.229.70.158 ssh-rsa " > ~/.ssh/known_hosts
  - SERVER_RSA=ssh-keyscan -t rsa "54.229.70.158"
  - echo "$SERVER_RSA" >>  ~/.ssh/known_hosts
  - git push live master
deploy:
  provider: script
  script: ./empty.sh
  skip_cleanup: true
  on:
    branch: dev
