version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: serverscripts/serversetup.sh
      timeout: 300
  ApplicationStart:
    - location: serverscripts/startserver.sh
      timeout: 100
  ApplicationStop
    - location serverscripts/stopserver.sh
      timeout: 100
